moia-oss/teleproto

.github/PULL_REQUEST_TEMPLATE.md
Adds the template below to remind us of version number increment because that's forgotten a lot...
=> Add a PR description template to remind of version number increment

.github/CODEOWNERS, build.sbt, src/main/scala/io/moia/protos/teleproto/PbResult.scala, src/main/scala/io/moia/protos/teleproto/ReaderImpl.scala, src/test/scala/io/moia/protos/teleproto/ProtocolBuffersTest.scala
* Previously the implementation failed fast at the first error
=> Collect all transformation errors reading a PB model into detached model

src/main/scala/io/moia/protos/teleproto/Reader.scala
This enables use to get partial results from nested structures.
For example, we can de-serialize an envelope for an event, even if the
payload of the envelope fails to parse.  This has the advantage, that
you can access the metadata to find out more about the message.
=> Add a teleproto Reader for PbResult

src/main/scala/io/moia/protos/teleproto/Writer.scala
No, i only fixed some docs. Can be included in the next release
=> writer writes protobuf

build.sbt, project/build.properties, project/plugins.sbt, src/main/scala/io/moia/protos/teleproto/Reader.scala, src/main/scala/io/moia/protos/teleproto/VersionedModelReader.scala, src/main/scala/io/moia/protos/teleproto/VersionedModelWriter.scala
- Update to latest scalaPB release, which is strictly suggested for users of scalaPB 0.10 or later
- Update to latest scapegoat
=> [Bump] Update libraries

.github/CODEOWNERS
=> Remove Markus Jura from Codeowner list

build.sbt, src/main/scala/io/moia/protos/teleproto/PbResult.scala, src/test/scala/io/moia/protos/teleproto/PbResultTest.scala
I'm not sure if I should bump the version right now.
Supersedes #16
=> Add convenience constructors for PbResult

build.sbt, src/main/scala/io/moia/protos/teleproto/FormatImpl.scala, src/main/scala/io/moia/protos/teleproto/MigrationImpl.scala, src/main/scala/io/moia/protos/teleproto/ReaderImpl.scala, src/main/scala/io/moia/protos/teleproto/WriterImpl.scala
Passing the context manually to every function is unwieldy.
=> Refactor to use macro bundles

build.sbt, src/main/scala/io/moia/protos/teleproto/Reader.scala, src/main/scala/io/moia/protos/teleproto/TestData.scala, src/main/scala/io/moia/protos/teleproto/Writer.scala, src/test/scala/io/moia/protos/teleproto/ReaderTest.scala, src/test/scala/io/moia/protos/teleproto/WriterTest.scala
We are missing many combinators for those type classes.
=> Flesh out Reader and Writer APIs

README.md, build.sbt
=> Update Scala versions and Publishing instructions

build.sbt, src/main/scala/io/moia/protos/teleproto/VersionedModelReader.scala
=> Fix build (docs)

README.md
- No. It's just an improvement in README.md
=> Fix readme typos and add sealed trait derivation example

build.sbt, src/main/scala/io/moia/protos/teleproto/VersionedModelReader.scala, src/main/scala/io/moia/protos/teleproto/VersionedModelWriter.scala, src/test/scala/io/moia/protos/teleproto/ProtocolBuffersRoundTripTest.scala
It's quite inconvenient in user code not to have constructors.
=> Add VersionedModelReader and VersionedModelWriter constructors

.github/workflows/run-tests.yml
=> Automerge update PRs

.github/CODEOWNERS
To have an additional pair of eyes on incoming PRs.
=> Add Alexander van der Werff as codeowner

build.sbt
=> Use sbt slash syntax (the old one is deprecated in sbt 1.5)

.github/CODEOWNERS
Opting out, since I did not spend much time on this project recently, but get a lot of PR requests.
=> Remove aquamatthias from CODEOWNERS

.github/workflows/merge-me.yaml, .github/workflows/run-tests.yml, .scala-steward.conf
- Run tests only on pull request and push to master
- Pin ScalaPB artifacts to 0.10 for the time being
- Modify update PR description to include current version
- Use merge me action v2
Closes #113, closes #116, closes #117, closes #127
=> Merge action v2

.github/CODEOWNERS
I can not contribute to this project.
=> Remove Jonas from codeowners

.github/CODEOWNERS
On second thought, I guess this is interesting.
Reverts moia-dev/teleproto#138
=> Revert "Remove Jonas from codeowners"

.scala-steward.conf, build.sbt, project/plugins.sbt
=> Update to ScalaPB 11

.scalafmt.conf, build.sbt, project/plugins.sbt, src/main/scala/io/moia/protos/teleproto/Format.scala, src/main/scala/io/moia/protos/teleproto/FormatImpl.scala, src/main/scala/io/moia/protos/teleproto/Migration.scala, src/main/scala/io/moia/protos/teleproto/MigrationImpl.scala, src/main/scala/io/moia/protos/teleproto/PbResult.scala, src/main/scala/io/moia/protos/teleproto/ProtocolBuffers.scala, src/main/scala/io/moia/protos/teleproto/Reader.scala, src/main/scala/io/moia/protos/teleproto/ReaderImpl.scala, src/main/scala/io/moia/protos/teleproto/VersionedModelReader.scala, src/main/scala/io/moia/protos/teleproto/VersionedModelWriter.scala, src/main/scala/io/moia/protos/teleproto/Writer.scala, src/main/scala/io/moia/protos/teleproto/WriterImpl.scala, src/main/scala/io/moia/protos/teleproto/backward.scala, src/main/scala/io/moia/protos/teleproto/forward.scala, src/main/scala/io/moia/protos/teleproto/trace.scala, src/test/scala/io/moia/protos/teleproto/DeadlineFormatTest.scala, src/test/scala/io/moia/protos/teleproto/HierarchicalProtocolBuffersTest.scala, src/test/scala/io/moia/protos/teleproto/OneOfProtocolBuffersTest.scala, src/test/scala/io/moia/protos/teleproto/ProtocolBuffersMigrationHierarchyTest.scala, src/test/scala/io/moia/protos/teleproto/ProtocolBuffersTest.scala, src/test/scala/io/moia/protos/teleproto/ReaderTest.scala, src/test/scala/io/moia/protos/teleproto/WriterTest.scala
=> Update scalapb-json4s, scala-collection-compat and sbt-scalafmt

build.sbt
=> Update to version 2.0 for MiMa check

src/main/scala/io/moia/protos/teleproto/ProtocolBuffers.scala
This fine should be done then.
=> Use proper macro invocation syntax

build.sbt, src/main/scala/io/moia/protos/teleproto/FormatImpl.scala, src/main/scala/io/moia/protos/teleproto/ReaderImpl.scala, src/main/scala/io/moia/protos/teleproto/WriterImpl.scala
This fixes some compilation errors in the Scala 3 branch. Of course not all of them. But more things are compiling now.
=> Don't pass the `Type` but use given `Type[T]` & `Quotes`

build.sbt, project/plugins.sbt
=> Commented out scapegoat so it doesnt prevent sbt initialization

src/main/scala-3/io/moia/protos/teleproto/FormatImpl.scala, src/main/scala-3/io/moia/protos/teleproto/ReaderImpl.scala, src/main/scala-3/io/moia/protos/teleproto/WriterImpl.scala
These are the changes from our mob programming session on 11th of February on the Scala 3 branch.
=> February 11 session

.github/workflows/scala-steward.yml
Instead of the MOIA internal Steward.
=> Add Scala Steward GitHub Actions workflow

.github/workflows/merge-me.yaml
The user name changed with the action.
=> Fix Mege Me action

.github/workflows/run-tests.yml, .github/workflows/scala-steward.yml
=> Add setup-sbt to scala-steward GitHub Action
